# Site settings
title: Rodrigo Schmitt
email: rsandrade@gmail.com
url: https://rodrigoschmitt.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "iOS,Developer,Swift,Objective-C,Git"
skills: "iOS Developer - Organizer of CocoaHeads Porto - Swift and Objective-C"
meta_author: Schmitt Rodrigo

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2b2b2b #80B3FF
  primary-rgb: "43,43,43" #"128,179,255"
  secondary: 444444 #FD6E8A
  secondary-dark: 333333 #A2122F

# Footer settings
footer:
  copyright: Rodrigo Schmitt
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rodrigoschmitt
  - title: facebook
    url: http://facebook.com/rodrigo.schmitt
  - title: bitbucket
    url: http://bitbucket.org/rsandrade
  - title: github
    url: http://github.com/rodrigoschmitt

# Postal address (add as many lines as necessary)
address:
  - line: Porto, Portugal

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
